---
- hosts: all
  tasks:
    - name: fichiers hosts
      lineinfile:
        path: /etc/hosts
        line: 172.19.30.172 ubuntu1.ming.lan
        state: present

    - name: enlever cowsay des playbooks ansible
      lineinfile:
        path: /etc/skel/.bashrc
        line: export ANSIBLE_NOCOWS=1
        state: present

    - name: umask
      replace:
        path: /etc/skel/.profile
        regexp: '^#umask [0-9]*'
        replace: 'umask 002'
      when: ansible_hostname == 'debian-ming'

    - name: transfert 1
      fetch:
        src: /etc/skel/.profile
        dest: /tmp/.profile
        flat: true
      when: ansible_hostname == 'debian-ming'

    - name: transfert 2
      copy:
        src: /tmp/.profile
        dest: /etc/skel/.profile
      when: ansible_hostname == 'poste2'
