---
- hosts: all
  tasks:
    - name: upgrade debian family
      apt:
        update_cache: true
        upgrade: full
      when: ansible_distribution_file_variety == 'Debian'

    - name: upgrade redhat family
      dnf:
        name: "*"
        state: latest
      when: ansible_distribution_file_variety == 'RedHat'

    - name: alternative aux deux tasks précédentes
      package:
        name: "*"
        state: latest
